### PR TITLE
Using SpriteText to display username on top of the box

### PR DESCRIPTION
**Pull request by carlosalvarez91**
- Initial form to add username
- Using SpriteText to display name on top of each box facing to camera
- Cleaned up and re organise code

demo: https://meeting-room-3d.herokuapp.com/

### CODE REVIEW

**Comment by AidanNelson** [comment]
Hi @carlosalvarez91 and @tehsphinx and @urbanL1fe !

Very cool to see the way you are building out this template as an educational platform.  I would love to hear more about how you plan to use this project.  

Also, did you intend to open this pull request?  Some of the changes seem like they would help with the original template.  Others seem specific to your project, but perhaps we could find a way to incorporate them as examples.  What do you think?

**Comment by tehsphinx** [comment]
@carlosalvarez91 could answer the original intent of the PR. It definitely doesn't make sense to merge all that is in here.

**Comment by carlosalvarez91** [comment]
Hi @AidanNelson I did a pull request in February, re-structured, cleanup the project and I added a floating text with the username on top of the box. 
Months later we used that repo for a hackathlon to build a 3D classroom,
Yes, probably doesn't make sense to merge all this, I can make though PR with the improvements I made originally in Feb.

**Comment by AidanNelson** [comment]
@carlosalvarez91 Just wanted to follow up on this.  This looks like an exciting project and I would love to get some of the cleanup elements merged.  The goal of this template is to provide a (somewhat) un-opinionated scaffolding.  Do you think there is an easy way to pull the cleanup from this PR branch?

**Pull request closed without merging**
